Repository maroon-studio/maroon-studio, pull requests merged in 2024-06, with the labels that each got.

#19 feat: add open animation to desktop and mobileservices dropdown menu
  package-lock.json
  src/components/expandIcon/index.js
  src/components/mobileNavbarDropdown/index.js
  src/components/navbar/index.js
  src/components/navbar/index.style.js
  src/images/maroonStudio-expandPolygon.png
Labels: Feature (feat:)

#22 Navbar fix
  gatsby-config.js
  package-lock.json
  package.json
  src/components/hamburgerMenu/index.style.js
  src/components/logo/index.js
  src/components/mobileNavbarDropdown/index.js
  src/components/mobileNavbarDropdown/index.style.js
  src/components/navbar/index.js
  src/components/navbar/index.style.js
  src/images/maroonStudio-navwbarServicesArrow.png
  src/images/maroonStudio-onlineMarketingServiceIcon.png
  src/images/maroonStudio-seoServiceIcon.png
  src/images/maroonStudio-socialMediaManagementServiceIcon.png
  src/images/maroonStudio-websitesServiceIcon.png
  src/pages/index.js
Labels: Bug Fix (fix:), Feature (feat:)

#25 fix: replace footer social media icons using graphql
  src/templates/index/footer/index.js
Labels: Bug Fix (fix:)

#26 fix: change favicon image
  src/images/icon.png
Labels: Bug Fix (fix:)

#29 fix: fix lack of .htaccess file
  gatsby-config.js
  package-lock.json
  package.json
Labels: Bug Fix (fix:)

#32 refactor: temporary hide of social media icons
  src/templates/index/footer/index.style.js
Labels: Code Refactoring (refactor:)

#30 feat: add mobile-services-dropdown subtitles
  src/components/mobileNavbarDropdown/index.js
  src/components/mobileNavbarDropdown/index.style.js
Labels: Feature (feat:)

#31 feat: add desktop-services-dropdown subtitles
  src/components/navbar/index.js
  src/components/navbar/index.style.js
Labels: Feature (feat:)

#33 fix: real-values-section values layout
  src/components/realValueSampel/index.style.js
Labels: Bug Fix (fix:)

#35 fix: add images for sections sampel
  src/images/maroonStudio-bigMarketingOnlineIcon.png
  src/images/maroonStudio-bigSeoIcon.png
  src/images/maroonStudio-bigSocialMediaManagementIcon.png
  src/images/maroonStudio-bigWebistesIcon.png
Labels: Bug Fix (fix:)

#34 feat: add our-services-list-section
  src/components/ourServicesListSampel/index.js
  src/components/ourServicesListSampel/index.style.js
  src/pages/index.js
  src/templates/index/ourServicesListSection/index.js
  src/templates/index/ourServicesListSection/index.style.js
Labels: Feature (feat:)
