Repository maroon-studio/maroon-studio, pull requests merged in 2024-05, with the labels that each got.

#15 fix: fix general problem with navbar
  src/components/expandIcon/index.js
  src/components/expandIcon/index.style.js
  src/components/hamburgerMenu/index.js
  src/components/hamburgerMenu/index.style.js
  src/components/mobileNavbarDropdown/index.js
  src/components/mobileNavbarDropdown/index.style.js
  src/components/navbar/index.js
  src/components/navbar/index.style.js
  src/templates/index/hero/index.js
Labels: tag: dev, type: bug

#16 refactor: change in layout organization
  src/components/hamburgerMenu/index.js
  src/components/layout/index.js
  src/components/layout/index.style.js
  src/components/navbar/index.js
  src/pages/index.js
  src/templates/index/hero/index.js
Labels: tag: dev, type: refactor

#18 fix: fix 404 page outdated layout import
  src/pages/404.js
Labels: tag: ci/cd, tag: bug, type: fix
